version: "3.9"
services:
  backend:
    container_name: blog-backend
    build: ./
    depends_on:
      - database
    environment:
      - HOST=localhost
      - PORT=6060
      - DB_HOST=database
      - DB_PORT=5555
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=brianhoang-blog
    ports:
      - "6060:6060"
  database:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres
      - POSTGRES_DB = brianhoang-blog
    ports:
      - '5555:5432'
    volumes:
      - "database:/var/lib/postgresql/data"
    restart: on-failure

volumes:
  database: